---
- name: Install packages
  become: yes
  package:
    name:
      - bash-completion
      - git
      - nano
      - python3-pip
      - tmux
      - vim

- name: Install RedHat specific packages
  become: yes
  dnf:
    name:
      - iptables-utils
  when: ansible_os_family == 'RedHat'

- name: Configure Python debug server variables
  lineinfile:
    path: ".bashrc"
    line: "{{ item }}"
  with_items:
    - export DEBUGGER_TYPE=pydev
    - export DEBUGGER_PORT=9999
    - export DEBUGGER_HOST=192.168.122.1

- name: Configure time sync
  become: yes
  lineinfile:
    path: /etc/cron.hourly/chronyc
    create: yes
    line: sudo chronyc makestep
    mode: 0755
  when: ansible_os_family == 'RedHat'

- name: Sync time
  become: yes
  command: "{{ item }}"
  with_items:
    - chronyc 'burst 4/4'
    - chronyc makestep
  when: ansible_os_family == 'RedHat'

- name: Create Git clones
  git:
    repo: "https://opendev.org/openstack/{{ item }}.git"
    dest: "{{ item }}"
    update: no
    depth: 5
  with_items:
    - devstack
    - neutron

- name: Copy local.conf
  template:
    src: local.conf.j2
    dest: devstack/local.conf
    force: no

- name: Copy restack.sh
  copy:
    src: restack.sh
    dest: devstack/restack.sh
    mode: 0755

- name: Copy .tmux.conf
  copy:
    src: ~/.tmux.conf
    dest: .tmux.conf
  ignore_errors: True

- name: Copy test_server.bin
  copy:
    src: "{{ ds_test_server_path }}"
    dst: "test_server.bin"
  ignore_errors: True

- name: Create /opt/stack
  become: yes
  file:
    path: /opt/stack
    state: directory
    owner: "stack"

- name: For compatibility with some scripts create hard link /mnt/host
  become: yes
  ansible.builtin.file:
    src: /opt/stack
    dest: /mnt/host
    owner: "stack"
    state: link

- name: Synchronize local development files
  synchronize:
    src: "~/openstack/{{ item }}"
    dest: "/opt/stack/"
    rsync_opts:
      - "--exclude=.tox"
  with_items: "{{ ds_sync_folders }}"

- name: Install os-log-merger
  become: yes
  pip:
    name: os-log-merger
    executable: pip

- name: Install helper scripts
  become: yes
  pip:
    chdir: /opt/stack/devstack-helpers
    editable: yes
    name: .
    executable: pip

- name: Run restack.sh
  command:
    chdir: devstack/
    cmd: ./restack.sh

- name: Install bash completion
  become: yes
  shell:
    cmd: openstack complete > /etc/bash_completion.d/osc.bash_completion
    creates: /etc/bash_completion.d/osc.bash_completion
