---
ds_sync_folders:
  - barbican-tempest-plugin
  - designate-tempest-plugin
  - devstack-helpers
  - octavia
  - octavia-dashboard
  - octavia-lib
  - octavia-tempest-plugin
  - ovn-octavia-provider
  - tempest
ds_test_server_path: "{{ lookup('env', 'HOME') }}/openstack/test_server.bin"
